version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    # entrypoint会覆盖Dockerfile中的entrypoint command会覆盖Dockerfile中的cmd 并且会先执行entrypoint 再执行command
    # 通过wait-for.sh等待postgres启动 再使用start.sh迁移数据库 最后通过command启动api
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"] # wait for postgres to start before starting the api
    command: ["/app/main"]
